import type { Client, Employee, Ticket } from "./types";

/**
 * Mock data for the UI phase. Every panel reads from here so the screens stay
 * consistent; swap these exports for database/API calls when the backend lands.
 */

const AVATAR = "https://lh3.googleusercontent.com/aida-public/";

export const employees: Employee[] = [
  {
    id: "EMP-402",
    name: "Marcus Vance",
    initials: "MV",
    title: "Lead Field Engineer",
    department: "Field Operations",
    skillLevel: "Senior Engineer",
    email: "m.vance@apexindustrial.com",
    phone: "(312) 555-0194",
    status: "on_site",
    location: "Fab Unit 4, Bay C-12",
    joinedOn: "2019-03-11",
    avatarUrl:
      AVATAR +
      "AB6AXuAbKBKn8x4CteFXLcz1xbp7mHOivm69yeyvLm1Tl41rjp4EqYN--01N-gZluFnLZxjoyiYkvsIY46uHeRri-CKufqBEk1wzvryK0U2CFEVzzvLQJO0RhIXButrvr7vw5Qr1boRkmWAUOTq2tAu3Wf4GnHIsK3vD_q5cEiQbOJndEALQ1yJZS39nvq4hmpfTq0_X4Wjdke1eTf6lJPV8767iQtDasL5axIz7vybNqhdXjo3Pr5BBg5rn",
  },
  {
    id: "EMP-204",
    name: "Elena Rostova",
    initials: "ER",
    title: "Safety Officer",
    department: "Field Safety",
    skillLevel: "Supervisor",
    email: "e.rostova@apexindustrial.com",
    phone: "(312) 555-0142",
    status: "in_transit",
    location: "Staging Yard B",
    joinedOn: "2020-07-02",
    avatarUrl:
      AVATAR +
      "AB6AXuBnNsAyrmMgGbu_a_c8mgjmWN_9D7x_eddbGZ9pGjLllOLBwgT7FVV3E2p-7QAQdhmXUGJCf8zvh-vivXOQG1kK70PXP08QJ-XsvujoJ_GNdqtE4ZxtWQNHPP5FTW_-5PW_jgYLbaXEERLJ9ixO1TraqrfVQERgfLvIexNuO8SgWUBaWUXbFOAEJqjlrQ80HUb5yWuBcp2Rr6MTTnd2cOQDb_EmWOszlcYrNAsIjjPD8-GBvScDTtnP",
  },
  {
    id: "EMP-503",
    name: "David Chen",
    initials: "DC",
    title: "Telemetry Specialist",
    department: "Hardware Telemetry",
    skillLevel: "Level 2 Diagnostics",
    email: "d.chen@apexindustrial.com",
    phone: "(312) 555-0177",
    status: "remote",
    location: "Remote Telemetry Bridge",
    joinedOn: "2021-01-18",
  },
  {
    id: "EMP-119",
    name: "Sarah Lin",
    initials: "SL",
    title: "Electrical Specialist",
    department: "Infrastructure",
    skillLevel: "Senior Engineer",
    email: "s.lin@apexindustrial.com",
    phone: "(312) 555-0108",
    status: "on_site",
    location: "Substation 02",
    joinedOn: "2018-10-29",
  },
  {
    id: "EMP-311",
    name: "Sarah Jenkins",
    initials: "SJ",
    title: "Lead Infrastructure Tech",
    department: "Infrastructure",
    skillLevel: "Senior Engineer",
    email: "s.jenkins@apexindustrial.com",
    phone: "(312) 555-0163",
    status: "available",
    location: "HQ Dispatch",
    joinedOn: "2017-05-22",
    avatarUrl:
      AVATAR +
      "AB6AXuAMpuMVCqlcit-AmjpMLd3VjSHe5y3Kww62yQwfjdGuXFE8okdggSnAqC74dNRTXKotpHC7S9kuiTG6iVy3Vty7nTnpe5FYmqAWB9lfLV9ziyaSborjoGvHvPTDWSPP-1DL3afABK_eulBI-Vi_c0l2dKZrXiZeAeWMbTaC9fOnFj7pkUR4uGbi0M9LuSY0kAQDSf0jDJV9wltLnKIPG7fvAjDdQfY1wxuhaYp47RBlMEtc3iqfPSYc",
  },
  {
    id: "EMP-227",
    name: "Marcus Chen",
    initials: "MC",
    title: "Network Safety Officer",
    department: "Network Operations",
    skillLevel: "Level 2 Diagnostics",
    email: "m.chen@apexindustrial.com",
    phone: "(312) 555-0121",
    status: "available",
    location: "HQ Dispatch",
    joinedOn: "2022-02-14",
  },
  {
    id: "EMP-158",
    name: "Raj Patel",
    initials: "RP",
    title: "Diagnostics Engineer",
    department: "Hardware Telemetry",
    skillLevel: "Level 3 Diagnostics",
    email: "r.patel@apexindustrial.com",
    phone: "(312) 555-0185",
    status: "available",
    location: "Lab 3",
    joinedOn: "2020-11-09",
    avatarUrl:
      AVATAR +
      "AB6AXuBmvtj4YSqKsKK2zt5GfdA6ytt7yIl12JYZDORjNPJDie-pBgeNcI1gzocRot8_-gEMhQho_Y7s0ZR7_8rvp3PfV8of0qsCEq13fcj1d6Qlh43KZXRrY9h2QVWh_TUU3p9zc5wUXc6AhC4GDf5BGrf5MEt0aD9SR_okMsdzxAJ42T-Q4LCP7OE5UO5F9UqWDidtVJ1MhA5MYqefKm1HEN9AfkIdR6q26MU21R-qRSrOMbf83Uq2FAiQ",
  },
  {
    id: "EMP-376",
    name: "Kristin Alvarez",
    initials: "KA",
    title: "Field Lead",
    department: "Field Operations",
    skillLevel: "Supervisor",
    email: "k.alvarez@apexindustrial.com",
    phone: "(312) 555-0139",
    status: "on_site",
    location: "Pacific Chem Plant",
    joinedOn: "2019-08-05",
  },
  {
    id: "EMP-289",
    name: "David Ross",
    initials: "DR",
    title: "Electrical Specialist",
    department: "Infrastructure",
    skillLevel: "Level 2 Diagnostics",
    email: "d.ross@apexindustrial.com",
    phone: "(312) 555-0150",
    status: "on_site",
    location: "Substation 02",
    joinedOn: "2021-06-21",
    avatarUrl:
      AVATAR +
      "AB6AXuAM53sL_ObtCMp-VETY_AQCEM07re8qnpQYUnd399yhxhPIiOZieKvQ95AyUAuP2leMZIl3sTGOwb1cxx9EGhv-hYVcQekSFSqCJpS8V2oyWxZbCN17DFjXZzgJR5YjIddEsy13xrJmC_lSeMaMkDqzxRUkYEI-rSEFnejmRVmMy-9WUOqRARl3oOTroEJqtVX_pSqrYpeONh_WM3tQO6-Z7u7vzZFunfjAwq7iixactF__GJLmU69J",
  },
  {
    id: "EMP-445",
    name: "Liam Zhang",
    initials: "LZ",
    title: "Field Technician",
    department: "Field Operations",
    skillLevel: "Level 1 Field Tech",
    email: "l.zhang@apexindustrial.com",
    phone: "(312) 555-0116",
    status: "off_duty",
    location: "—",
    joinedOn: "2024-04-01",
  },
];

/** Signed-in users for each panel (until auth exists). */
export const currentEmployeeId = "EMP-402";
export const currentClientId = "CL-1001";

export const adminUser = {
  name: "Alex Mercer",
  role: "Operations Lead",
  avatarUrl:
    AVATAR +
    "AB6AXuDRHEEgLGpV9SKqfdqMZetxGrragfmoBJ1Ms8-hGrMzUVXtvH8kMYyMgMHSGovW29CnYSkA3XUAV3yJUatTgX3aJymQd5soRw0f-bi_GsKhcNf_S2xJhEgpUCinvyQEgy__cpOTTCC7_Vk6MvuIUentm5Os_Grcmu7NYTOKRJs50ep6bMEZZ3YeXhyOoaxhqg3q-Gz2nFiOYy1LqW-QhVacovpmkNuESG6oTeD3PqlY6ynz_EcNbF5P",
};

export const careAgent = {
  id: "CC-441",
  name: "Nadia Perera",
  role: "Customer Care Dispatcher",
};

export const clients: Client[] = [
  {
    id: "CL-1001",
    name: "Midwest Energy Unit 4",
    facility: "Apex Midwest Fabrication Unit 4",
    address: "10440 S. Calumet River Corridor, Chicago IL 60617",
    contractRef: "#MW-ENG-2021-99",
    tier: "Enterprise Tier-1",
    contactName: "Arthur Pendelton",
    contactRole: "Plant Operations Director",
    contactEmail: "a.pendelton@midwestenergy.com",
    contactPhone: "(312) 555-8821",
    accessLevel: "Level-3 Industrial Security Cleared",
    safetyProtocol: "ARC-Flash PPE 40 Cal/cm² Required",
  },
  {
    id: "CL-1002",
    name: "Commonwealth Grid Corp",
    facility: "Substation 02 — Joliet",
    address: "2201 Rock Run Dr, Joliet IL 60436",
    contractRef: "#CGC-PWR-2022-14",
    tier: "Enterprise Tier-1",
    contactName: "Helen Okafor",
    contactRole: "Grid Reliability Manager",
    contactEmail: "h.okafor@commonwealthgrid.com",
    contactPhone: "(815) 555-2290",
    accessLevel: "Utility Escort Required",
    safetyProtocol: "High-Voltage Switching Permit",
  },
  {
    id: "CL-1003",
    name: "Apex Heavy Power Co.",
    facility: "Control Room West",
    address: "880 Industrial Pkwy, Gary IN 46406",
    contractRef: "#AHP-CTL-2023-07",
    tier: "Standard Tier-2",
    contactName: "Victor Hale",
    contactRole: "Controls Supervisor",
    contactEmail: "v.hale@apexheavypower.com",
    contactPhone: "(219) 555-4410",
    accessLevel: "Badge Access Only",
    safetyProtocol: "Lockout/Tagout Standard",
  },
  {
    id: "CL-1004",
    name: "Pacific Industrial Chemical",
    facility: "Compressor House 1",
    address: "4500 Harbor Blvd, Long Beach CA 90802",
    contractRef: "#PIC-MEC-2024-03",
    tier: "Enterprise Tier-1",
    contactName: "Grace Moreno",
    contactRole: "Maintenance Director",
    contactEmail: "g.moreno@pacificchem.com",
    contactPhone: "(562) 555-7731",
    accessLevel: "Hazmat Escort Required",
    safetyProtocol: "Respirator + H2S Monitor",
  },
  {
    id: "CL-1005",
    name: "Apex Logistics Global Ltd.",
    facility: "Hub-North Chicago",
    address: "1200 W Fulton Market, Chicago IL 60607",
    contractRef: "#ALG-OPS-2022-31",
    tier: "Standard Tier-2",
    contactName: "John Doe",
    contactRole: "Facilities Liaison",
    contactEmail: "johndoe@apex-logistics.com",
    contactPhone: "+1 (312) 555-0194",
    accessLevel: "Visitor Badge",
    safetyProtocol: "Hi-Vis Vest Required",
  },
];

export const tickets: Ticket[] = [
  {
    id: "TKT-8492",
    jobId: "JOB-8942",
    title: "High-Pressure Turbine Calibration & Vibration Dampening",
    assetTag: "TURBINE-04",
    clientId: "CL-1001",
    createdById: "EMP-402",
    ownerId: "EMP-402",
    participantIds: ["EMP-204", "EMP-503", "EMP-119"],
    startDate: "2026-09-28",
    endDate: "2026-10-08",
    description:
      "Rotor spindle 04 in Turbine Bay C-12 is showing elevated vibration signatures above the 0.04 G-RMS threshold. Full calibration of the high-pressure stage and replacement of the vibration dampening harness is required before the unit can return to peak load.",
    priority: "high",
    category: "Mechanical / Calibration",
    status: "in_progress",
    subtasks: [
      {
        id: "ST-1",
        title: "Initial Diagnostics & Safety Lockout",
        description:
          "OSHA zero-energy state validated, telemetry bridge spliced, base vibration signatures benchmarked.",
        assigneeIds: ["EMP-402", "EMP-204"],
        estimate: "6 h",
        status: "done",
        progress: 100,
        completedAt: "2026-09-29T09:30:00",
      },
      {
        id: "ST-2",
        title: "Mechanical Disassembly & Rotor Inspection",
        description:
          "End-cap extraction completed. Micron-scale magnetic eddy-current tests clean. Bearing collar upgraded.",
        assigneeIds: ["EMP-402", "EMP-119"],
        estimate: "2 d",
        status: "done",
        progress: 100,
        completedAt: "2026-10-01T16:15:00",
      },
      {
        id: "ST-3",
        title: "High-Tolerance Recalibration & Sensor Alignment",
        description: "Calibrating piezo-electric strain sensors & dynamic harmonic stabilizers along 3-axis plane.",
        assigneeIds: ["EMP-503"],
        estimate: "1.5 d",
        status: "in_progress",
        progress: 68,
        dueDate: "2026-10-05",
      },
      {
        id: "ST-4",
        title: "Full Load Stress Test & Certification Sign-Off",
        description: "6-hour continuous peak RPM validation, thermal envelope inspection, and final engineering seal.",
        assigneeIds: ["EMP-402"],
        estimate: "1 d",
        status: "pending",
        progress: 0,
        dueDate: "2026-10-08",
      },
    ],
    attachments: [
      { id: "A-1", name: "vibration_fft_baseline.png", size: "1.2 MB", kind: "image", label: "RAW CAPTURE" },
      { id: "A-2", name: "rotor_inspection_report.pdf", size: "860 KB", kind: "pdf", label: "INSPECTION" },
      { id: "A-3", name: "sensor_log_0900.txt", size: "45 KB", kind: "log", label: "STDOUT STREAM" },
    ],
    activity: [
      {
        id: "AC-1",
        kind: "system",
        authorName: "System Controller",
        authorRole: "Automation",
        at: "2026-09-28T08:05:00",
        text: "Ticket state changed from Open to In Progress. Crew of 4 dispatched to Fab Unit 4.",
        visibleToEmployees: true,
      },
      {
        id: "AC-2",
        kind: "employee",
        authorId: "EMP-402",
        authorName: "Marcus Vance",
        authorRole: "Lead Field Engineer",
        at: "2026-10-04T10:30:00",
        text: "Piezo-electric strain sensors aligned to ±0.02 microns tolerance. Lubricant injection cycle calibrated. Awaiting auxiliary rotor spin test at 1,800 RPM.",
        visibleToEmployees: true,
      },
      {
        id: "AC-3",
        kind: "customer-care",
        authorId: "CC-441",
        authorName: "Nadia Perera",
        authorRole: "Customer Care",
        at: "2026-10-04T11:42:00",
        text: "Arthur Pendelton called asking for spin-test vibration readings. Please share the FFT capture once the 1,800 RPM run completes.",
        visibleToEmployees: true,
      },
    ],
    priorityRequests: [],
    billing: {
      invoiceId: "INV-9284",
      issuedOn: "2026-10-01",
      dueDate: "2026-11-04",
      taxRate: 0.08,
      lines: [
        { description: "Lead Field Engineer — on-site labour", qty: 42, unit: "hr", rate: 145 },
        { description: "Safety Officer — lockout supervision", qty: 12, unit: "hr", rate: 110 },
        { description: "Telemetry Specialist — remote calibration", qty: 18, unit: "hr", rate: 125 },
        { description: "Ceramic bearing collar kit", qty: 1, unit: "kit", rate: 1420 },
        { description: "Vibration dampening harness", qty: 2, unit: "ea", rate: 860 },
        { description: "Site mobilisation & logistics", qty: 1, unit: "lot", rate: 950 },
      ],
    },
    updatedAt: "2026-10-04T11:42:00",
  },
  {
    id: "TKT-8495",
    jobId: "JOB-8946",
    title: "Auxiliary Turbine Cooling Line 4B Pressure Fluctuation",
    assetTag: "COOL-4B",
    clientId: "CL-1001",
    createdById: "EMP-402",
    ownerId: "EMP-402",
    participantIds: ["EMP-503", "EMP-119"],
    startDate: "2026-10-06",
    endDate: "2026-10-10",
    description:
      "Auxiliary turbine cooling line 4B pressure erratic fluctuation observed between 03:00 - 05:30 EST. Transducer unit relay tripping intermittent safety overrides. Requesting complete sensor recalibration and valve seating test.",
    priority: "high",
    category: "Hydraulics & Pneumatics",
    status: "open",
    subtasks: [
      {
        id: "ST-1",
        title: "Zero-Energy Safety Lockout & Pressure Bleed",
        description:
          "Execute standard LOTO on circuit breaker CB-118 and secondary isolation valves. Verify analog zero gauge before removing transducer coupling.",
        assigneeIds: ["EMP-402"],
        estimate: "45 min",
        status: "pending",
        progress: 0,
      },
      {
        id: "ST-2",
        title: "Transducer Recalibration & Telemetry Loop Test",
        description:
          "Bench calibrate digital pressure transducers PT-401 and PT-402 with certified master gauge. Run 5-point curve and transmit telemetry check to central SCADA.",
        assigneeIds: ["EMP-503", "EMP-119"],
        estimate: "90 min",
        status: "pending",
        progress: 0,
      },
    ],
    attachments: [{ id: "A-1", name: "pressure_trend_0300.csv", size: "210 KB", kind: "sheet", label: "SCADA EXPORT" }],
    activity: [
      {
        id: "AC-1",
        kind: "system",
        authorName: "System Controller",
        authorRole: "Automation",
        at: "2026-10-03T16:20:00",
        text: "Ticket created by Marcus Vance and queued for dispatch triage.",
        visibleToEmployees: true,
      },
    ],
    priorityRequests: [],
    updatedAt: "2026-10-03T16:20:00",
  },
  {
    id: "TKT-8488",
    jobId: "JOB-8939",
    title: "Substation Transformer Core Rewind & Oil Purge",
    assetTag: "XFMR-SUB-02",
    clientId: "CL-1002",
    createdById: "EMP-119",
    ownerId: "EMP-119",
    participantIds: ["EMP-402", "EMP-289"],
    startDate: "2026-09-20",
    endDate: "2026-10-05",
    description:
      "Transformer T-2 failed dissolved gas analysis. Core rewind of the secondary winding and a full insulating oil purge and refill are required, followed by client witness testing.",
    priority: "critical",
    category: "Electrical / Power",
    status: "awaiting_signoff",
    subtasks: [
      {
        id: "ST-1",
        title: "De-energise & Switching Isolation",
        description: "Coordinate switching order with grid operator and confirm isolation of T-2.",
        assigneeIds: ["EMP-119"],
        estimate: "4 h",
        status: "done",
        progress: 100,
        completedAt: "2026-09-20T13:00:00",
      },
      {
        id: "ST-2",
        title: "Oil Drain, Filter & Purge",
        description: "Drain 12,000 L of insulating oil, vacuum-filter and stage for disposal.",
        assigneeIds: ["EMP-289"],
        estimate: "2 d",
        status: "done",
        progress: 100,
        completedAt: "2026-09-23T17:40:00",
      },
      {
        id: "ST-3",
        title: "Secondary Winding Core Rewind",
        description: "Rewind secondary winding to OEM spec and megger-test insulation resistance.",
        assigneeIds: ["EMP-119", "EMP-402"],
        estimate: "5 d",
        status: "done",
        progress: 100,
        completedAt: "2026-10-01T15:10:00",
      },
      {
        id: "ST-4",
        title: "Client Witness Test & Sign-Off",
        description: "Ratio, impedance and DGA re-test witnessed by client reliability team.",
        assigneeIds: ["EMP-119"],
        estimate: "1 d",
        status: "in_progress",
        progress: 70,
        dueDate: "2026-10-05",
      },
    ],
    attachments: [
      { id: "A-1", name: "dga_results_t2.pdf", size: "540 KB", kind: "pdf", label: "LAB REPORT" },
      { id: "A-2", name: "megger_readings.xlsx", size: "96 KB", kind: "sheet", label: "TEST DATA" },
    ],
    activity: [
      {
        id: "AC-1",
        kind: "employee",
        authorId: "EMP-119",
        authorName: "Sarah Lin",
        authorRole: "Electrical Specialist",
        at: "2026-10-03T15:00:00",
        text: "Rewind complete and megger readings within tolerance. Waiting on client witness slot.",
        visibleToEmployees: true,
      },
      {
        id: "AC-2",
        kind: "customer-care",
        authorId: "CC-441",
        authorName: "Nadia Perera",
        authorRole: "Customer Care",
        at: "2026-10-04T09:15:00",
        text: "Client confirmed witness test window for Oct 5, 08:00. Helen Okafor will attend in person.",
        visibleToEmployees: true,
      },
    ],
    priorityRequests: [],
    updatedAt: "2026-10-04T09:15:00",
  },
  {
    id: "TKT-8481",
    jobId: "JOB-8931",
    title: "High-Voltage SCADA Relay Diagnostics & Firmware Patch",
    assetTag: "SCADA-RLY-9",
    clientId: "CL-1003",
    createdById: "EMP-503",
    ownerId: "EMP-503",
    participantIds: ["EMP-158", "EMP-227"],
    startDate: "2026-09-30",
    endDate: "2026-10-09",
    description:
      "Protective relay RLY-9 reporting intermittent comms loss with the SCADA master. Diagnose the fibre link, patch relay firmware to v4.2.1 and re-run end-to-end trip tests.",
    priority: "medium",
    category: "Controls & SCADA",
    status: "in_progress",
    subtasks: [
      {
        id: "ST-1",
        title: "Fibre Link & Comms Trace",
        description: "OTDR trace of the relay fibre link and port error counters.",
        assigneeIds: ["EMP-227"],
        estimate: "6 h",
        status: "done",
        progress: 100,
        completedAt: "2026-10-01T12:00:00",
      },
      {
        id: "ST-2",
        title: "Telemetry Testing",
        description: "Loop telemetry tests between RLY-9 and SCADA master under load.",
        assigneeIds: ["EMP-503", "EMP-158"],
        estimate: "1 d",
        status: "in_progress",
        progress: 40,
      },
      {
        id: "ST-3",
        title: "Firmware Patch v4.2.1",
        description: "Stage, flash and verify relay firmware checksum.",
        assigneeIds: ["EMP-158"],
        estimate: "4 h",
        status: "pending",
        progress: 0,
      },
      {
        id: "ST-4",
        title: "End-to-End Trip Test",
        description: "Simulated fault injection and trip timing verification.",
        assigneeIds: ["EMP-503"],
        estimate: "6 h",
        status: "pending",
        progress: 0,
      },
    ],
    attachments: [{ id: "A-1", name: "otdr_trace_rly9.png", size: "780 KB", kind: "image", label: "OTDR CAPTURE" }],
    activity: [],
    priorityRequests: [],
    updatedAt: "2026-10-03T10:00:00",
  },
  {
    id: "TKT-8476",
    jobId: "JOB-8920",
    title: "Emergency Compressor Bearing Overhaul & Balancing",
    assetTag: "CMP-BRG-01",
    clientId: "CL-1004",
    createdById: "EMP-204",
    ownerId: "EMP-376",
    participantIds: ["EMP-204", "EMP-445"],
    startDate: "2026-09-25",
    endDate: "2026-10-02",
    description:
      "Compressor C-1 drive-end bearing temperature exceeded alarm limits. Emergency overhaul of the bearing assembly and dynamic balancing of the impeller.",
    priority: "critical",
    category: "Mechanical / Calibration",
    status: "in_progress",
    subtasks: [
      {
        id: "ST-1",
        title: "Rapid Triage",
        description: "Thermal imaging and vibration spectrum to confirm bearing failure mode.",
        assigneeIds: ["EMP-376"],
        estimate: "4 h",
        status: "in_progress",
        progress: 60,
      },
      {
        id: "ST-2",
        title: "Bearing Extraction & Replacement",
        description: "Extract DE bearing, inspect journal, install replacement assembly.",
        assigneeIds: ["EMP-376", "EMP-445"],
        estimate: "2 d",
        status: "pending",
        progress: 0,
      },
      {
        id: "ST-3",
        title: "Impeller Dynamic Balancing",
        description: "Two-plane balancing to ISO 1940 G2.5.",
        assigneeIds: ["EMP-376"],
        estimate: "1 d",
        status: "pending",
        progress: 0,
      },
      {
        id: "ST-4",
        title: "Return to Service",
        description: "Run-in test and handover to plant operations.",
        assigneeIds: ["EMP-204"],
        estimate: "6 h",
        status: "pending",
        progress: 0,
      },
    ],
    attachments: [{ id: "A-1", name: "thermal_c1_de.png", size: "2.1 MB", kind: "image", label: "THERMAL" }],
    activity: [
      {
        id: "AC-1",
        kind: "customer-care",
        authorId: "CC-441",
        authorName: "Nadia Perera",
        authorRole: "Customer Care",
        at: "2026-10-03T08:10:00",
        text: "Client escalated: plant running on standby compressor. SLA breached — please send revised ETA today.",
        visibleToEmployees: true,
      },
    ],
    priorityRequests: [
      {
        id: "PR-1",
        from: "high",
        to: "critical",
        reason: "Standby compressor at 95% duty, client risk of full shutdown.",
        requestedBy: "Nadia Perera (CC-441)",
        at: "2026-10-02T17:30:00",
        status: "approved",
      },
    ],
    updatedAt: "2026-10-03T08:10:00",
  },
  {
    id: "TKT-8465",
    jobId: "JOB-8907",
    title: "Hydraulic Pressure Sensor Calibration Fault",
    assetTag: "HYD-PS-12",
    clientId: "CL-1001",
    createdById: "EMP-402",
    ownerId: "EMP-402",
    participantIds: ["EMP-158"],
    startDate: "2026-10-01",
    endDate: "2026-10-12",
    description:
      "Press line 2 hydraulic pressure sensors drifting by up to 4% between shifts. Recalibrate sensor bank and replace the faulty signal conditioner.",
    priority: "medium",
    category: "Hydraulics & Pneumatics",
    status: "in_progress",
    subtasks: [
      {
        id: "ST-1",
        title: "Sensor Drift Survey",
        description: "Log drift across all 12 sensors over two shifts.",
        assigneeIds: ["EMP-158"],
        estimate: "2 d",
        status: "done",
        progress: 100,
        completedAt: "2026-10-03T18:00:00",
      },
      {
        id: "ST-2",
        title: "Signal Conditioner Replacement",
        description: "Swap conditioner SC-4 and verify output scaling.",
        assigneeIds: ["EMP-402"],
        estimate: "4 h",
        status: "in_progress",
        progress: 25,
      },
      {
        id: "ST-3",
        title: "Bank Recalibration",
        description: "Five-point calibration on each sensor against master gauge.",
        assigneeIds: ["EMP-402", "EMP-158"],
        estimate: "1 d",
        status: "pending",
        progress: 0,
      },
    ],
    attachments: [],
    activity: [],
    priorityRequests: [],
    billing: {
      invoiceId: "INV-9301",
      issuedOn: "2026-10-03",
      dueDate: "2026-11-02",
      taxRate: 0.08,
      lines: [
        { description: "Diagnostics Engineer — drift survey", qty: 16, unit: "hr", rate: 120 },
        { description: "Lead Field Engineer — conditioner swap", qty: 4, unit: "hr", rate: 145 },
        { description: "Signal conditioner SC-4", qty: 1, unit: "ea", rate: 690 },
      ],
    },
    updatedAt: "2026-10-03T18:00:00",
  },
  {
    id: "TKT-8472",
    jobId: "JOB-8915",
    title: "Conveyor Belt Speed Sync Issue — Line 3",
    assetTag: "CNV-L3",
    clientId: "CL-1005",
    createdById: "EMP-402",
    ownerId: "EMP-402",
    participantIds: ["EMP-445"],
    startDate: "2026-09-14",
    endDate: "2026-09-19",
    description: "Line 3 conveyor sections drifting out of sync under load. Retune VFD parameters and replace encoder.",
    priority: "low",
    category: "Electrical / Power",
    status: "completed",
    subtasks: [
      {
        id: "ST-1",
        title: "Encoder Replacement",
        description: "Replace failed encoder on drive section 3B.",
        assigneeIds: ["EMP-445"],
        estimate: "3 h",
        status: "done",
        progress: 100,
        completedAt: "2026-09-16T11:00:00",
      },
      {
        id: "ST-2",
        title: "VFD Parameter Retune",
        description: "Retune master/follower speed loop.",
        assigneeIds: ["EMP-402"],
        estimate: "5 h",
        status: "done",
        progress: 100,
        completedAt: "2026-09-18T15:30:00",
      },
    ],
    attachments: [],
    activity: [],
    priorityRequests: [],
    updatedAt: "2026-09-19T10:00:00",
  },
  {
    id: "TKT-8450",
    jobId: "JOB-8890",
    title: "HVAC Terminal Heating Sensor Failure",
    assetTag: "HVAC-T7",
    clientId: "CL-1001",
    createdById: "EMP-402",
    ownerId: "EMP-402",
    participantIds: ["EMP-227"],
    startDate: "2026-09-02",
    endDate: "2026-09-06",
    description: "Terminal unit T7 heating sensor reading open-circuit. Replace sensor and recommission zone controller.",
    priority: "medium",
    category: "HVAC",
    status: "completed",
    subtasks: [
      {
        id: "ST-1",
        title: "Sensor Replacement",
        description: "Replace PT1000 sensor and verify wiring.",
        assigneeIds: ["EMP-402"],
        estimate: "2 h",
        status: "done",
        progress: 100,
        completedAt: "2026-09-03T10:00:00",
      },
      {
        id: "ST-2",
        title: "Zone Controller Recommission",
        description: "Reload setpoints and verify trend logs for 48h.",
        assigneeIds: ["EMP-227"],
        estimate: "2 d",
        status: "done",
        progress: 100,
        completedAt: "2026-09-05T16:00:00",
      },
    ],
    attachments: [],
    activity: [],
    priorityRequests: [],
    billing: {
      invoiceId: "INV-9177",
      issuedOn: "2026-09-07",
      dueDate: "2026-10-07",
      taxRate: 0.08,
      lines: [
        { description: "Lead Field Engineer — sensor replacement", qty: 3, unit: "hr", rate: 145 },
        { description: "Network Safety Officer — recommissioning", qty: 6, unit: "hr", rate: 110 },
        { description: "PT1000 sensor", qty: 1, unit: "ea", rate: 85 },
      ],
    },
    updatedAt: "2026-09-06T17:00:00",
  },
  {
    id: "TKT-8439",
    jobId: "JOB-8876",
    title: "Pneumatic Cylinder Pressure Leak — Staging Bay 2",
    assetTag: "PNU-SB2",
    clientId: "CL-1005",
    createdById: "EMP-311",
    ownerId: "EMP-311",
    participantIds: ["EMP-402"],
    startDate: "2026-08-25",
    endDate: "2026-08-28",
    description: "Pneumatic cylinder bank in staging bay 2 losing pressure overnight. Locate and repair leaks.",
    priority: "low",
    category: "Hydraulics & Pneumatics",
    status: "completed",
    subtasks: [
      {
        id: "ST-1",
        title: "Ultrasonic Leak Survey",
        description: "Survey all fittings with ultrasonic detector.",
        assigneeIds: ["EMP-311"],
        estimate: "3 h",
        status: "done",
        progress: 100,
        completedAt: "2026-08-26T12:00:00",
      },
      {
        id: "ST-2",
        title: "Seal Replacement",
        description: "Replace rod seals on cylinders 3 and 7.",
        assigneeIds: ["EMP-402"],
        estimate: "4 h",
        status: "done",
        progress: 100,
        completedAt: "2026-08-27T15:00:00",
      },
    ],
    attachments: [],
    activity: [],
    priorityRequests: [],
    updatedAt: "2026-08-28T09:00:00",
  },
];

export const categories = [
  "Mechanical / Calibration",
  "Electrical / Power",
  "Controls & SCADA",
  "Hydraulics & Pneumatics",
  "HVAC",
  "Safety & Compliance",
] as const;

export const departments = [
  "Field Operations",
  "Infrastructure",
  "Hardware Telemetry",
  "Field Safety",
  "Network Operations",
] as const;

export const skillLevels = ["Level 1 Field Tech", "Level 2 Diagnostics", "Level 3 Diagnostics", "Senior Engineer", "Supervisor"] as const;
